### PR TITLE
updated Pipfile and Pipfile.lock

### PR DESCRIPTION
**Pull request by SankBad**
This PR will update the Pipfile and Pipfile.lock
I tested the image locally and it's working perfectly.

### CODE REVIEW

**Review by Shreyanand — CHANGES_REQUESTED** [review]
Are the dev packages causing any issue?

**Comment by SankBad** [comment]
I haven't tried to create an image with dev packages. Let me try.

**Comment by SankBad** [comment]
Hi @Shreyanand , 

I tried image with dev packages. It's not causing any issue. 
I updated Pipfile and Pipfile.lock with dev packages

**Comment by Shreyanand** [comment]
cool, squash commits and I'll merge :)

**Comment by SankBad** [comment]
Thanks @Shreyanand 
Squashed all the commits.

**Review by Shreyanand — APPROVED** [review]

**Pull request merged**
