### PR TITLE
Spelling error detection notebook for public repo

### PR DESCRIPTION
**Pull request by SankBad**
This PR will add a spelling error detection notebook for public repo of configuration file analysis.

### CODE REVIEW

**Comment by SankBad** [comment]
Need to add data downloading procedure in the notebook.

**Review by MichaelClifford — APPROVED** [review]
LGTM @SankBad. 

I don't think you have to add the data downloading procedure to this notebook. Since the data is used across notebooks, it might make more sense to just have it as a script in `src/data/` or as its own notebook and handle that in a separate PR.

**Comment by Shreyanand** [comment]
> LGTM @SankBad.
> 
> I don't think you have to add the data downloading procedure to this notebook. Since the data is used across notebooks, it might make more sense to just have it as a script in `src/data/` or as its own notebook and handle that in a separate PR.

Thanks @MichaelClifford, I just created #4 for this.

**Comment by SankBad** [comment]
I am closing this PR and creating another PR with an updated notebook.
I made this repo public after creating this PR and hence, I am not able to make any more changes in this branch. 

Reference: 
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility

Changing a private repository to a public repository
If a private repository is made public, each of its private forks is turned into a standalone private repository and becomes the parent of its own new repository network. Private forks are never automatically made public because they could contain sensitive commits that shouldn't be exposed publicly.

**Pull request closed without merging**
