### PR TITLE
added blog material

### PR DESCRIPTION
**Pull request by SankBad**
This PR will add blog material for a blog on configuration file analysis.

### CODE REVIEW

**Comment by SankBad** [comment]
@oindrillac , 

I made all the suggested changes. I tested the site locally, reference links as well as tables are properly rendered now. 
Video on adding remote content was indeed useful. :clap: 
Once this PR is merged, I will create another PR for adding entries in `content-sources.yaml` and `toc.yaml` in operate first repo.

**Review by oindrillac — APPROVED** [review]
Thanks for making the changes @SankBad. LGTM :ship: 
Do you want to go ahead and squash commits?

**Comment by SankBad** [comment]
Squashed all the commits

**Review by Shreyanand — APPROVED** [review]
LGTM :balloon:

**Pull request merged**
